import HybridAppModule from '@expensify/react-native-hybrid-app';
import Onyx from 'react-native-onyx';
import type {OnyxEntry} from 'react-native-onyx';
import CONFIG from '@src/CONFIG';
import CONST from '@src/CONST';
import ONYXKEYS from '@src/ONYXKEYS';
import type {Account, Credentials, HybridApp, Session, TryNewDot} from '@src/types/onyx';
import {closeReactNativeApp, setReadyToShowAuthScreens, setUseNewDotSignInPage} from './actions/HybridApp';
import Log from './Log';
import {getCurrentUserEmail} from './Network/NetworkStore';
import {shouldUseOldApp} from './TryNewDotUtils';

function isAnonymousUser(sessionParam: OnyxEntry<Session>): boolean {
    return sessionParam?.authTokenType === CONST.AUTH_TOKEN_TYPES.ANONYMOUS;
}

let currentHybridApp: OnyxEntry<HybridApp>;
let currentTryNewDot: OnyxEntry<TryNewDot>;
let currentCredentials: OnyxEntry<Credentials>;
let currentSession: OnyxEntry<Session>;
let currentAccount: OnyxEntry<Account>;

// Synchronous in-memory latch ensuring the OldDot bridge sign-in runs at most once per sign-in.
// Unlike the Onyx-based guards, it takes effect immediately and blocks the same-tick burst of subscription callbacks.
let hasStartedOldDotSignIn = false;

Onyx.connectWithoutView({
    key: ONYXKEYS.HYBRID_APP,
    callback: (hybridApp) => {
        currentHybridApp = hybridApp;
        signInToOldDotAndChooseExperience(hybridApp, currentTryNewDot, currentCredentials, currentSession, currentAccount);
    },
});

Onyx.connectWithoutView({
    key: ONYXKEYS.NVP_TRY_NEW_DOT,
    callback: (tryNewDot) => {
        currentTryNewDot = tryNewDot;
        signInToOldDotAndChooseExperience(currentHybridApp, tryNewDot, currentCredentials, currentSession, currentAccount);
    },
});

Onyx.connectWithoutView({
    key: ONYXKEYS.CREDENTIALS,
    callback: (credentials) => {
        currentCredentials = credentials;
        signInToOldDotAndChooseExperience(currentHybridApp, currentTryNewDot, credentials, currentSession, currentAccount);
    },
});

Onyx.connectWithoutView({
    key: ONYXKEYS.SESSION,
    callback: (session: OnyxEntry<Session>) => {
        currentSession = session;
        signInToOldDotAndChooseExperience(currentHybridApp, currentTryNewDot, currentCredentials, session, currentAccount);
    },
});

Onyx.connectWithoutView({
    key: ONYXKEYS.ACCOUNT,
    callback: (account: OnyxEntry<Account>) => {
        currentAccount = account;
        signInToOldDotAndChooseExperience(currentHybridApp, currentTryNewDot, currentCredentials, currentSession, account);
    },
});

let activePolicyID: OnyxEntry<string>;
Onyx.connectWithoutView({
    key: ONYXKEYS.NVP_ACTIVE_POLICY_ID,
    callback: (newActivePolicyID) => {
        activePolicyID = newActivePolicyID;
    },
});

/**
 * Signs the user into OldDot when session and credentials are available,
 * then decides whether to stay in NewDot or switch to OldDot based on `nvp_tryNewDot`.
 */
function signInToOldDotAndChooseExperience(
    hybridApp: OnyxEntry<HybridApp>,
    tryNewDot: OnyxEntry<TryNewDot>,
    credentials: OnyxEntry<Credentials>,
    session: OnyxEntry<Session>,
    account: OnyxEntry<Account>,
) {
    if (!CONFIG.IS_HYBRID_APP) {
        return;
    }

    if (!session?.authToken || !hybridApp?.useNewDotSignInPage) {
        return;
    }

    if (isAnonymousUser(session)) {
        setReadyToShowAuthScreens(true);
        return;
    }

    if (!credentials?.autoGeneratedLogin || !credentials?.autoGeneratedPassword || account?.requiresTwoFactorAuth === undefined || account?.needsTwoFactorAuthSetup === undefined) {
        return;
    }

    // Skip if we're already in the signing in flow, preventing multiple calls to signInToOldDot
    if (session?.autoAuthState === CONST.AUTO_AUTH_STATE.SIGNING_IN) {
        return;
    }

    // Skip if the bridge sign-in has already been started for this sign-in. This synchronous latch
    // is set before calling the bridge, so it also blocks subsequent subscription callbacks fired in the same burst.
    if (hasStartedOldDotSignIn) {
        return;
    }
    hasStartedOldDotSignIn = true;

    Log.info(`[HybridApp] Performing sign-in on OldDot side`);
    HybridAppModule.signInToOldDot({
        autoGeneratedLogin: credentials.autoGeneratedLogin,
        autoGeneratedPassword: credentials.autoGeneratedPassword,
        authToken: session.authToken,
        email: getCurrentUserEmail() ?? '',
        // eslint-disable-next-line rulesdir/no-default-id-values
        policyID: activePolicyID ?? '',
        signingInWithSAML: hybridApp?.signingInWithSAML ?? false,
    });

    if (tryNewDot !== undefined) {
        setUseNewDotSignInPage(false).then(() => {
            if (shouldUseOldApp(tryNewDot) && (!account?.needsTwoFactorAuthSetup || account?.requiresTwoFactorAuth)) {
                closeReactNativeApp({shouldSetNVP: false, isTrackingGPS: false});
            } else {
                setReadyToShowAuthScreens(true);
            }
        });
    }
}

/**
 * Resets the one-shot latch so a later sign-in (after sign-out or account switch) can run the OldDot bridge sign-in again.
 */
function resetOldDotSignInState() {
    hasStartedOldDotSignIn = false;
}

export {resetOldDotSignInState};
