import CONFIG from '@src/CONFIG';
import CONST from '@src/CONST';
import ONYXKEYS from '@src/ONYXKEYS';
import type {Account, Credentials, HybridApp, Session, TryNewDot} from '@src/types/onyx';

import type {OnyxEntry} from 'react-native-onyx';

import HybridAppModule from '@expensify/react-native-hybrid-app';
import Onyx from 'react-native-onyx';

import {closeReactNativeApp, setReadyToShowAuthScreens, setUseNewDotSignInPage} from './actions/HybridApp';
import Log from './Log';
import {getCurrentUserEmail} from './Network/NetworkStore';
import {shouldUseOldApp} from './TryNewDotUtils';

function isAnonymousUser(sessionParam: OnyxEntry<Session>): boolean {
    return sessionParam?.authTokenType === CONST.AUTH_TOKEN_TYPES.ANONYMOUS;
}

let currentHybridApp: OnyxEntry<HybridApp>;
let currentTryNewDot: OnyxEntry<TryNewDot>;
let currentCredentials: OnyxEntry<Credentials>;
let currentSession: OnyxEntry<Session>;
let currentAccount: OnyxEntry<Account>;

Onyx.connectWithoutView({
    key: ONYXKEYS.HYBRID_APP,
    callback: (hybridApp) => {
        currentHybridApp = hybridApp;
        signInToOldDotAndChooseExperience(hybridApp, currentTryNewDot, currentCredentials, currentSession, currentAccount);
    },
});

Onyx.connectWithoutView({
    key: ONYXKEYS.NVP_TRY_NEW_DOT,
    callback: (tryNewDot) => {
        currentTryNewDot = tryNewDot;
        signInToOldDotAndChooseExperience(currentHybridApp, tryNewDot, currentCredentials, currentSession, currentAccount);
    },
});

Onyx.connectWithoutView({
    key: ONYXKEYS.CREDENTIALS,
    callback: (credentials) => {
        currentCredentials = credentials;
        signInToOldDotAndChooseExperience(currentHybridApp, currentTryNewDot, credentials, currentSession, currentAccount);
    },
});

Onyx.connectWithoutView({
    key: ONYXKEYS.SESSION,
    callback: (session: OnyxEntry<Session>) => {
        currentSession = session;
        signInToOldDotAndChooseExperience(currentHybridApp, currentTryNewDot, currentCredentials, session, currentAccount);
    },
});

Onyx.connectWithoutView({
    key: ONYXKEYS.ACCOUNT,
    callback: (account: OnyxEntry<Account>) => {
        currentAccount = account;
        signInToOldDotAndChooseExperience(currentHybridApp, currentTryNewDot, currentCredentials, currentSession, account);
    },
});

let activePolicyID: OnyxEntry<string>;
Onyx.connectWithoutView({
    key: ONYXKEYS.NVP_ACTIVE_POLICY_ID,
    callback: (newActivePolicyID) => {
        activePolicyID = newActivePolicyID;
    },
});

/**
 * Signs the user into OldDot when session and credentials are available,
 * then decides whether to stay in NewDot or switch to OldDot based on `nvp_tryNewDot`.
 */
function signInToOldDotAndChooseExperience(
    hybridApp: OnyxEntry<HybridApp>,
    tryNewDot: OnyxEntry<TryNewDot>,
    credentials: OnyxEntry<Credentials>,
    session: OnyxEntry<Session>,
    account: OnyxEntry<Account>,
) {
    if (!CONFIG.IS_HYBRID_APP) {
        return;
    }

    if (!session?.authToken || !hybridApp?.useNewDotSignInPage) {
        Log.info(`[HybridApp] Waiting for session authToken and NewDot sign-in page before signing in on OldDot side`);
        return;
    }

    if (isAnonymousUser(session)) {
        setReadyToShowAuthScreens(true);
        return;
    }

    if (!credentials?.autoGeneratedLogin || !credentials?.autoGeneratedPassword) {
        Log.info(`[HybridApp] Waiting for auto-generated credentials before signing in on OldDot side`);
        return;
    }

    // Skip if we're already in the signing in flow, preventing multiple calls to signInToOldDot
    if (session?.autoAuthState === CONST.AUTO_AUTH_STATE.SIGNING_IN) {
        Log.info(`[HybridApp] Already signing in on OldDot side, skipping`);
        return;
    }

    Log.info(`[HybridApp] Performing sign-in on OldDot side`);
    HybridAppModule.signInToOldDot({
        autoGeneratedLogin: credentials.autoGeneratedLogin,
        autoGeneratedPassword: credentials.autoGeneratedPassword,
        authToken: session.authToken,
        email: getCurrentUserEmail() ?? '',
        // eslint-disable-next-line rulesdir/no-default-id-values
        policyID: activePolicyID ?? '',
        signingInWithSAML: hybridApp?.signingInWithSAML ?? false,
    });

    // If the tryNewDot NVP or the 2FA account flags haven't arrived yet, we can't decide whether to redirect to OldDot.
    // Default to staying in NewDot so the user isn't stuck on the sign-in page; the redirect decision can still happen later when the NVP arrives.
    if (tryNewDot === undefined || account?.requiresTwoFactorAuth === undefined || account?.needsTwoFactorAuthSetup === undefined) {
        Log.info(`[HybridApp] Missing tryNewDot NVP or 2FA account flags, staying in NewDot`);
        setUseNewDotSignInPage(false);
        setReadyToShowAuthScreens(true);
        return;
    }

    setUseNewDotSignInPage(false).then(() => {
        if (shouldUseOldApp(tryNewDot) && (!account?.needsTwoFactorAuthSetup || account?.requiresTwoFactorAuth)) {
            closeReactNativeApp({shouldSetNVP: false, isTrackingGPS: false});
        } else {
            setReadyToShowAuthScreens(true);
        }
    });
}
